name: ezy_form
description: "Easy to handle form in Flutter without any complexity. Easy to use and customize."
version: 0.0.1
homepage: https://github.com/samderlust/flutter_easy_form

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
